export const products =[
  {
    "id": 1,
    "name": "Focal Clear Open-Back Headphones",
    "image": "",
    "brand": "Focal",
    "rating": 5,
    "price": 890,
    "design": "Over-Ear, Open Back",
    "connectivity": "Wired",
    "description": "The Focal Clear will bring you 5% short of Utopia. Meaning the Focal Clear is about 95% of its bigger brother, the Focal Utopia. The Clear has some of the best detail, resolution and dynamics in its price range however if you are looking for a little more low-end we recommend looking elsewhere as the Clear does have a brighter sound signature. Headphones.com has partnered with Focal to secure exclusive rights to Focal's last manufacturing run of the Focal Clear. The Focal Clear is now discontinued and only available for $890 (SAVE $600!) from Headphones.com! As it is the last manufacturing run and a Final Sale item, the Focal Clear is final sale and cannot be returned. However, the Clear is fully covered under Focal's manufacturer warranty.",
    "warranty": "3 years",
    "material": "(40mm) Al/Mg 'M'-dome",
    "color": "Gray"
  },
  {
    "id": 2,
    "name": "Hifiman Sundara Planar Magnetic Headphones - 2020 Edition",
    "image": "",
    "brand": "Hifiman",
    "rating": 5,
    "price": 299,
    "design": "Over-Ear, Open-Back",
    "connectivity": "Wired",
    "description": "The Sundara utilizes its ultra-thin diaphragm to deliver low distortion and high sensitivity so the the Sundara can be utilized with a number of different sources, including your mobile devices! The planar magnetic drivers of the Sundara guarantee fast transient response, excellent planar bass, and a frequency range of 6 hz - 75 hz.",
    "warranty": "1 year",
    "material": "Lightweight aluminum",
    "color": "Black"
  },
  {
    "id": 3,
    "name": "Moondrop Blessing 2 In-Ear Monitor Headphones",
    "image": "",
    "brand": "Moondrop",
    "rating": 4.5,
    "price": 319.99,
    "design": "In-ear",
    "connectivity": "Wired",
    "description": "he Moondrop Blessings 2 In-Ear monitor headphones are equipped with a five driver hybrid setup on each side having One 10mm paper cone diaphragm unit for handling the bass section, Dual Softears D-Mid-A driver units for handling the Mid-range frequencies, and Dual Knowles SWFK units for handling the Treble sections. The drivers work together flawlessly with no distortion between them at all. The resulting sound output is very smooth, the drivers are tuned in a way to match the Harman Target Curve, it offers a quick and deep bass response, natural, lush vocals, and smooth and sweet treble response.",
    "warranty": "1 year",
    "material": "Medical Grade Resin Shell",
    "color": "White"
  },
  {
    "id": 4,
    "name": "Thieaudio Monarch MKII In-Ear Monitors",
    "image": "",
    "brand": "Thieaudio",
    "rating": 4.9,
    "price": 999.99,
    "design": "In-ear",
    "connectivity": "Wired",
    "description": "Thieaudio's goal for the Monarch MKII was to enhance its technical performance and introduce a more balanced tuning, while staying true to the original spirit of this monitor. We took this opportunity to update all of the internal drivers, swapping them out for their latest counterparts and rearranging their configurations to achieve an even more optimal performance.?",
    "warranty": "3 years",
    "material": "Soft braided paracord material",
    "color": "Brown"
  },
  {
    "id": 5,
    "name": "Sennheiser HD 800S",
    "image": "",
    "brand": "Sennheiser",
    "rating": 5,
    "price": 1799.95,
    "design": "Over-Ear, Open Back",
    "connectivity": "Wired",
    "description": "An update on the well-regarded HD 800, the Sennheiser HD 800 S Stereo Headphones comprises a pair of open-back headphones designed for use in studio situations, particularly when referencing between monitors and cans. Its 56mm transducer is housed in stainless steel, while its headband and mounting utilize industrial, aerospace-grade materials to emphasize durability at a relatively light weight of 11.6 oz.",
    "warranty": "2 years",
    "material": "330 grams, aluminum",
    "color": "Black"
  },
  {
    "id": 6,
    "name": "Moondrop Variations Tribrid In-Ear Monitor Headphones",
    "image": "",
    "brand": "Moondrop",
    "rating": 4.6,
    "price": 52.09,
    "design": "Closed-Back, In-ear",
    "connectivity": "Wireless",
    "description": "The Moondrop Variations Tribrid In-Ear Monitor Headphone is the latest set of high-resolution in-ear monitors featuring an advanced tribrid driver combination. The pair houses a premium five driver configuration housing dual Sonion EST drivers paired with dual midrange Balanced Armature drivers, and a 10mm large LCP diaphragm Dynamic driver. Moondrop has designed the pair with a 3D-printed medical-grade resin material cavity with sandblasted stainless steel face panels for a rich and premium look.",
    "warranty": "1 year",
    "material": "Stainless steel + medical-grade resin ",
    "color": "Black"
  },
  {
    "id": 7,
    "name": "Hifiman Arya Planar Magnetic Over-Ear Headphones - Stealth Magnets Edition",
    "image": "",
    "brand": "Hifiman",
    "rating": 5,
    "price": 129.99,
    "design": "Over-Ear, Open Back",
    "connectivity": "Wired",
    "description": "Arya is the culmination of HifiMan s work. Never has a company brought this kind of Planar performance at this price point. Fast, wide soundstage and mind-blowing detail make the Arya a must-listen. HifiMan Arya features a driver based on the HE1000 V2 headphones, one of the best drivers on the market in our opinion, which raises the sonic characteristics to a considerably higher level than similarly priced products.",
    "warranty": "1 year",
    "material": "High-quality metal headband with extra strength and a special high-grade plastic",
    "color": "Black"
  },
  {
    "id": 8,
    "name": "Anker Soundcore Liberty Air 2 Pro Active Noise Cancelling True Wireless Bluetooth Earbuds - Black",
    "image": "",
    "brand": "Anker",
    "rating": 4.5,
    "price": 39.99,
    "design": "In-ear",
    "connectivity": "Wireless",
    "description": "Soundcore Liberty Air 2 Pro are an incredibly advanced pair of wireless earbuds. With up to 26 hours of total play time off of one charge, you can experience your favorite music at all times of the day. Purenote technology allows for a higher quality listening experience, active noise cancelling technology cancels out outside noises intelligently, while HearID provides EQ customization. All three come together to make sure your listening experience is truly yours.",
    "warranty": "1 year",
    "material": "Lightweight polymer",
    "color": "Black"
  },
  {
    "id": 9,
    "name": "Logitech H390 ClearChat Comfort USB Headset - Black; Noise Cancellation Microphone; Inline Volume; Mute Controls",
    "image": "",
    "brand": "Logitech",
    "rating": 4.3,
    "price": 19.65,
    "design": "Over-Ear",
    "connectivity": "Wired",
    "description": "Extend your comfort with a padded headband and ear pads. A rotating, noise-canceling microphone reduces background chatter, and convenient in-line volume and mute controls let you adjust audio on the fly.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  },
  {
    "id": 10,
    "name": "Apple Earpods Wired Earbuds - White; Lightning Connector; In-line Remote Controls; Built-in Microphone",
    "image": "",
    "brand": "Apple",
    "rating": 4.9,
    "price": 19.99,
    "design": "In-ear",
    "connectivity": "Wired",
    "description": "Unlike traditional, circular earbuds, the design of the EarPods is defined by the geometry of the ear. Which makes them more comfortable for more people than any other earbud-style headphones. The speakers inside the EarPods have been engineered to maximize sound output and minimize sound loss, which means you get high-quality audio. The EarPods with Lightning Connector also include a built-in remote that lets you adjust the volume, control the playback of music and video, and answer or end calls with a pinch of the cord.",
    "warranty": "1 year",
    "material": "Plastic, rubber",
    "color": "White"
  },
  {
    "id": 11,
    "name": "Anker Soundcore Life Q20 Hybrid Active Noise Cancelling Wireless Bluetooth Headphones - Black; 40H Playtime; Hi-Res Audio; Deep Bass; Memory Foam Ear Cups",
    "image": "",
    "brand": "Anker",
    "rating": 4.3,
    "price": 25,
    "design": "Over-Ear",
    "connectivity": "Wireless",
    "description": "Custom oversized 40 mm dynamic drivers produce Hi-Res Audio - a certification only awarded to audio devices capable of producing exceptional sound. Life Q20 active noise cancelling headphones reproduce your music with extended high frequencies that reach up to 40 kHz for extraordinary clarity and detail.",
    "warranty": "1 year",
    "material": "Polymer, aluminum",
    "color": "Black"
  },
  {
    "id": 12,
    "name": "Sony WH-1000XM5 Active Noise Canceling Wireless Bluetooth Over-Ear Headphones - Black",
    "image": "",
    "brand": "Sony",
    "rating": 4.1,
    "price": 35.99,
    "design": "Over-Ear",
    "connectivity": "Wireless",
    "description": "No matter the situation, you can connect and listen without distraction when you use the black WH-1000XM5 Noise-Canceling Wireless Over-Ear Headphones from Sony. The latest edition of Sony's heralded ANC headphones, the WH-1000XM5 goes further to boost clarity. Active noise cancellation uses two processors and eight mics to filter out more high and midrange sound. Four of the mics are beamforming and use Precise Voice Pickup technology to better isolate your voice for pristine hands-free calls. What you hear is also high-quality thanks to Hi-Res Audio support via a newly developed 30mm driver. Add in a lightweight design, additional convenience features, and up to 30 hours of power, and you have a pair of headphones that you can wear all day.",
    "warranty": "3 years",
    "material": "Plastic lightweight design",
    "color": "Black"
  },
  {
    "id": 13,
    "name": "JLab GO Work Bluetooth Wireless Office Headset - Black",
    "image": "",
    "brand": "Jlab",
    "rating": 3.9,
    "price": 15.99,
    "design": "Over-Ear",
    "connectivity": "Wireless",
    "description": "The GO Work Wireless On-Ear Headset from JLab will be your new best friend at the office. Featuring 45+ hours of playtime to get you through a full work week and Bluetooth multipoint, you can connect to 2 devices at once so you can transition from mobile to laptop without touching any settings. The GO Work Headset also features 2 microphones for clear calling, a retractable boom mic with LED quick mute indicator, multi-functional buttons for controls, and 2 EQ settings for Work or Music mode.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  },
  {
    "id": 14,
    "name": "Sony WH-1000XM4 Active Noise Canceling Wireless Bluetooth Over-Ear Headphones - Black; Built-in Microphone; Up to 30 hours Listening Time",
    "image": "",
    "brand": "Sony",
    "rating": 4.2,
    "price": 19.99,
    "design": "Over-Ear",
    "connectivity": "Wireless",
    "description": "No matter where you go, the black Sony WH-1000XM4 Wireless Noise-Canceling Over-Ear Headphones deliver pristine sound quality while automatically adjusting ambient sound according to your activity and registered locations, leaving your hands and mind free from the hassle of changing settings just to hear what you want to hear. Plus, the headphones detect when you're wearing them and start and stop your audio for you.",
    "warranty": "3 years",
    "material": "Lightweight aluminum",
    "color": "Black"
  },
  {
    "id": 15,
    "name": "Logitech USB H540 Wired Headset - Black; Adjustable Padded Headband; Easy On-ear Sound Controls; Noise-cancelling Rotating Boom Microphone",
    "image": "",
    "brand": "Logitech",
    "rating": 4.1,
    "price": 25.65,
    "design": "On-ear",
    "connectivity": "Wired",
    "description": "Bring your Internet calls, music, movies and online videos to life with this precision-audio stereo headset. Simply plug the USB cord into your desktop or laptop computer to instantly immerse yourself in pure, rich digital sound.",
    "warranty": "1 year",
    "material": "High-density plastic",
    "color": "Black"
  },
  {
    "id": 16,
    "name": "JLab Go Air Sport True Wireless Bluetooth Workout Earbuds - Black; C3 Clear Calling; Secure Earhook Sport Design; 32+ Hour Bluetooth Playtime; 3 EQ Sound Settings",
    "image": "",
    "brand": "Jlab",
    "rating": 3.8,
    "price": 15,
    "design": "In-ear",
    "connectivity": "Wireless",
    "description": "Power through your hardest or easiest workout with the GO Air Sport, the perfect everyday sport earbud. With 32+ hours of total playtime, a secure and comfortable sport fit, and 3 custom sound settings, the GO Air Sport are mighty (and fun). Auto connect to your device and add some color to your workout.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  },
  {
    "id": 17,
    "name": "Beyerdynamic DT 770 Pro 80 Ohm Over-Ear Headphones - Gray; Passive Noise Cancellation; Soft Padded Headband",
    "image": "",
    "brand": "Beyerdynamic",
    "rating": 3.9,
    "price": 45,
    "design": "Over-Ear",
    "connectivity": "Wired",
    "description": "Beyerdynamic DT 770 Pro closed studio headphones provide professional-quality sound for critical listening applications. Whether you're in the control room or on the recording floor, DT 770 Pro headphones are made to deliver accurate sound while providing a very comfortable fit a real necessity for long sessions. You get an impressive 5Hz-35kHz frequency response, while the closed-ear design helps to minimize outside noise and orient the headphones' speakers to your ears correctly. Built to last and perform reliably, DT 770 headphones make a great addition to any studio.",
    "warranty": "1 year",
    "material": "Lightweight aluminum",
    "color": "Black"
  },
  {
    "id": 18,
    "name": "Beyerdynamic DT 990 Pro Open Back Wired Headphones - Black; Replaceable Ear Pads; Padded and Adjustable Spring Steel Headband",
    "image": "",
    "brand": "Beyerdynamic4.0",
    "rating": "",
    "price": 69.99,
    "design": "Over-Ear",
    "connectivity": "Wired",
    "description": "The DT 990 has been made for listening without stress. This open headphone features a pleasant sound and brilliant bass. The DT 990 gives a three-dimensional sound, that is, it reproduces all details of the various instruments of an orchestra as a unity. You will have a completely unique audio experience. Low headband pressure and a soft padded headband ensure a high comfort. The soft earpads can be easily replaced. The single-sided coiled cable can be extended and is fitted with a gold-vaporized stereo jack plug (3.5 mm) with an adapter that gives freedom of movement.",
    "warranty": "1 year",
    "material": "Stainless steel + resin ",
    "color": "Black"
  },
  {
    "id": 19,
    "name": "Audio-Technica ATH-M20X Professional Monitor Wired Headphones",
    "image": "",
    "brand": "Audio-Technica",
    "rating": 4.9,
    "price": 119.99,
    "design": "Over-Ear",
    "connectivity": "Wired",
    "description": "The ATH-M20x professional monitor headphones are a great introduction to the critically acclaimed M-Series line. Modern design and high-quality materials combine to deliver a comfortable listening experience, with enhanced audio and effective isolation. An excellent choice for tracking and mixing.",
    "warranty": "3 years",
    "material": "Lightweight aluminum",
    "color": "Black"
  },
  {
    "id": 20,
    "name": "Sony ZX Series Wired On-Ear Headphones, Black MDR-ZX110",
    "image": "",
    "brand": "Sony",
    "rating": 4.5,
    "price": 9,
    "design": "On-ear",
    "connectivity": "Wired",
    "description": "Sony headphones deliver pristine sound quality while automatically adjusting ambient sound according to your activity and registered locations, leaving your hands and mind free from the hassle of changing settings just to hear what you want to hear. Plus, the headphones detect when you're wearing them and start and stop your audio for you.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  },
  {
    "id": 21,
    "name": "JBL Tune 510BT: Wireless On-Ear Headphones with Purebass Sound - Blue",
    "image": "",
    "brand": "JBL",
    "rating": 4.6,
    "price": 49.65,
    "design": " On-ear",
    "connectivity": "Wireless",
    "description": "The JBL Tune 510BT headphones let you stream powerful JBL Pure Bass sound with no strings attached. Easy to use, with up to 40 hours of battery life and speed charge, they are super lightweight and comfortable. Grab them and fill your day with music!",
    "warranty": "2 years",
    "material": "High-density plastic",
    "color": "Blue"
  },
  {
    "id": 22,
    "name": "RORSOU R10 On-Ear Headphones with Microphone, Lightweight Folding Stereo Bass Headphones with 1.5M No-Tangle Cord, Portable Wired Headphones for Smartphone Tablet Computer MP3 / 4 (Black)",
    "image": "",
    "brand": "RORSOU",
    "rating": 4.6,
    "price": 13,
    "design": " On-ear",
    "connectivity": "Wired",
    "description": "RORSOU R10 headphones with microphone in bright colors are built meticulously with strong and sturdy plastic for long-lasting resilience and durability. Premium 4.9 ft (1.5m) nylon braiding cord doesn t tangle or kink, suitable for adults and Children.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  },
  {
    "id": 23,
    "name": "Anker Soundcore Life Q20 Hybrid Active Noise Cancelling Headphones, Wireless  Over-Ear Bluetooth Headphones, 40H Playtime, Hi-Res Audio, Deep Bass, Memory Foam Ear Cups, for Travel, Home Office",
    "image": "",
    "brand": "Anker",
    "rating": 4.5,
    "price": 59.99,
    "design": " Over-Ear",
    "connectivity": "Wireless",
    "description": "Incredible Sound Loved by 20 Million+ People. In the box you ll find a travel pouch to conveniently store Life Q20 active noise cancelling headphones in, a 3.5mm AUX cable to keep the music playing when you re low on battery, and a Micro USB cable to charge them with.",
    "warranty": "1 year",
    "material": "Lightweight polymer",
    "color": "Black"
  },
  {
    "id": 24,
    "name": "Beats Studio3 Wireless Noise Cancelling Over-Ear Headphones - Apple W1 Headphone Chip, Class 1 Bluetooth, 22 Hours of Listening Time, Built-in Microphone - Midnight Black (Latest Model)",
    "image": "",
    "brand": "Beats",
    "rating": 4.7,
    "price": 229.99,
    "design": " Over-Ear",
    "connectivity": "Wireless, Bluetooth, Wired, NFC",
    "description": "Beats Studio3 Wireless over-ear headphones delivers premium sound while blocking external noise with Active Noise Cancelling.",
    "warranty": "3 years",
    "material": "Plastic, rubber",
    "color": "Black"
  },
  {
    "id": 25,
    "name": "Bose SoundLink around-ear wireless headphones II- White",
    "image": "",
    "brand": "Bose",
    "rating": 4.6,
    "price": 229.99,
    "design": " Over-Ear",
    "connectivity": "Wireless,Bluetooth",
    "description": "Freedom. Convenience. The big advantages of wireless headphones. But Bose gives you a better wireless experience all around. Deep, immersive sound at any volume. Clearer calls at both ends of the communication. Seamless switching between two connected Bluetooth devices, so you ll never miss a call or that movie you re watching. Once you hear them, we think you ll agree they re the best-sounding wireless headphones you ll find anywhere.",
    "warranty": "3 years",
    "material": "Stainless steel + resin ",
    "color": "White"
  },
  {
    "id": 26,
    "name": "POWMEE P20 Kids Headphones Over-Ear Headphones for Kids/Teens/Boys/Girls/School with 94dB Volume Limited Adjustable Stereo Tangle-Free 3.5MM Jack Wire Cord for Fire Tablets/Travel/PC/Phones(Blue)",
    "image": "",
    "brand": "POWMEE",
    "rating": 4.6,
    "price": 13,
    "design": " Over-Ear",
    "connectivity": "Wired",
    "description": "High-quality stereo with rich and clear dynamic sound.Superb sound quality brings clear tone and 94dB Volume Limit.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Blue"
  },
  {
    "id": 27,
    "name": "Beats Solo3 Wireless On-Ear Headphones - Apple W1 Headphone Chip, Class 1 Bluetooth, 40 Hours of Listening Time, Built-in Microphone - Red (Latest Model)",
    "image": "",
    "brand": "Beats",
    "rating": 4.7,
    "price": 131.69,
    "design": " On-ear",
    "connectivity": "Wireless, Bluetooth, NFC",
    "description": "Beats Solo3 Wireless on-ear headphones immerse you in rich, award-winning sound everywhere you want to go. With up to 40 hours of battery life, it s your perfect everyday headphone. The Apple W1 chip delivers one-touch pairing with your Apple devices and unique features like Siri integration. The headphone stays true to its predecessor with bold styling and streamlined design. And since it s durable, foldable, and wireless, Beats Solo3 Wireless is the ultimate portable listening device.",
    "warranty": "3 years",
    "material": "Plastic, rubber",
    "color": "Red"
  },
  {
    "id": 28,
    "name": "Srhythm NC25 Active Noise Cancelling Headphones Bluetooth 5.3,ANC Stereo Headset Over-Ear with Hi-Fi,Mic,50H Playtime,Voice Assistant,Low Latency Game Mode",
    "image": "",
    "brand": "Srhythm",
    "rating": 3.4,
    "price": 65.99,
    "design": " Over-Ear",
    "connectivity": "Wireless, Wired",
    "description": "Ultra-light,Foldable,Rotatable ANC headphones,Extremely comfortable for all-day wear.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Green"
  },
  {
    "id": 29,
    "name": "LORELEI X6 Over-Ear Headphones with Microphone, Lightweight Foldable & Portable Stereo Bass Headphones with 1.45M No-Tangle, Wired Headphones for Smartphone Tablet MP3 / 4 (Space Black)",
    "image": "",
    "brand": "LORELEI",
    "rating": 4.4,
    "price": 16.5,
    "design": " Over-Ear",
    "connectivity": "Wired",
    "description": "These headphones with microphone adopt High-definition 40mm driver and compact earcups design, which deliver exceptionally clear sound with full dynamic range and rich bass and crisp mids. Effortless style and powerful sound let you tune into your own rhythms with the set of on-ear headphones.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  },
  {
    "id": 30,
    "name": "LORELEI X8 Over-Ear Wired Headphones with Microphone with 1.45m-Tangle-Free Nylon Line&3.5mm Plug,Lightweight Foldable & Portable Headphones for Smartphone,Tablet,Computer,Mp3/4(Dark Purple)",
    "image": "",
    "brand": "LORELEI",
    "rating": 4.5,
    "price": 13,
    "design": " Over-Ear",
    "connectivity": "Wired",
    "description": "These headphones with microphone adopt High-definition 40mm driver and compact earcups design, which deliver exceptionally clear sound with full dynamic range and rich bass and crisp mids. Effortless style and powerful sound let you tune into your own rhythms with the set of on-ear headphones.",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Purple"
  },
  {
    "id": 31,
    "name": "6S Wireless Bluetooth Headphones  Over-Ear, Hi-Fi Stereo Foldable Wireless Stereo Headsets Earbuds with Built-in Mic, Volume Control, FM for Phone/PC (Black & Gold)",
    "image": "",
    "brand": "6S",
    "rating": 4.3,
    "price": 19.99,
    "design": " Over-Ear",
    "connectivity": "Wireless, Bluetooth, Wired",
    "description": "High Definition Stereo Headphones, and advanced Wireless chip that aim to deliver you superior sound quality with high fidelity deep bass and crystal clear treble, Deep, accurate bass response, extended frequency range, rechargeable. Lose yourself in immersive music even in the lowest volume levels!",
    "warranty": "1 year",
    "material": "Plastic",
    "color": "Black"
  }
]
